"""
Flood Simulation Engine — Winter Garden FL Property
====================================================
2D raster-based physically-based flood model for the 2×2 km study area.

Governing equations implemented
---------------------------------
1. INFILTRATION — Horton exponential decay model
   f(t) = fc + (f0 − fc) × exp(−k × t)
   Cumulative: F(t) = fc·t + (f0−fc)/k × (1 − exp(−k·t))
   Net rainfall (runoff source): Pe(t) = max(P(t) − f(t), 0)  [mm/hr → m/s]

2. OVERLAND FLOW — Manning's equation in 2D diffusive wave form
   Unit discharge between adjacent cells:
     q = (1/n) × h^(5/3) × |S|^(1/2) × sign(S)     [m²/s]
   where S = Δη/Δx, η = h + z (water surface elevation)

3. 2D SHALLOW WATER EQUATIONS (local inertia approximation)
   This is the Bates et al. (2010) local inertia scheme — the core of
   LISFLOOD-FP — which simplifies the full SWE momentum equation by
   dropping the advection term (valid for Fr << 1, i.e., slow floodwater):

   Continuity:
     ∂h/∂t + ∂(hu)/∂x + ∂(hv)/∂y = Pe(t) − f(t)

   Momentum (simplified, per interface between cells i and j):
     q_new = [q_prev − g·h_flow·Δt·∂η/∂x] / [1 + g·Δt·n²·|q_prev|/h_flow^(7/3)]
     where h_flow = max(η_i, η_j) − max(z_i, z_j)

   Depth update (continuity on grid cell):
     h[i,j]_new = h[i,j] + (Δt/Δx)·(q_x_in − q_x_out + q_y_in − q_y_out) + Δt·Pe

4. LAKE STORAGE & OUTFLOW — broad-crested weir equation
   Volume-area-elevation (VAE) curve from lake-bed DEM.
   Outflow when lake level exceeds outlet elevation:
     Q_out = Cd · L · (h_lake − z_outlet)^(3/2)     [m³/s]
   where Cd ≈ 1.7 (broad crest), L = outlet width [m]

5. TIME STEP STABILITY — CFL condition
   Δt ≤ α · Δx / √(g · h_max)   (α = 0.5)

Scenarios simulated
-------------------
  flash_1hr_100yr      : 1-hr SCS Type II storm, 100-year return period
  flash_1hr_10yr       : 1-hr SCS Type II storm, 10-year return period
  sustained_12hr_100yr : 12-hr SCS Type II storm, 100-year return period
  sustained_12hr_10yr  : 12-hr SCS Type II storm, 10-year return period
  historical_20240212  : Real gauge data (USC00088788 Clermont FL, Feb 7–14 2024)
                         — requires precipitation/data/hyetograph_historical_20240212.csv
                           (generated by precipitation/fetch_noaa_gauge.py)

Physics note — local inertia vs full SWE
-----------------------------------------
This solver uses the Bates et al. (2010) LOCAL INERTIA approximation of the 2D
shallow water equations: the advection terms ∂(hu²)/∂x, ∂(huv)/∂y (and y-equivalents)
are omitted from the momentum equations. This is valid for sub-critical flows (Fr << 1)
and is the core of LISFLOOD-FP. The flash 1-hr 100-yr scenario reaches peak velocities
~3.5 m/s → Fr > 1 in concentrated flow paths, where the local inertia approximation
underestimates peak velocity and over-spreads the flood front. A Godunov-type Roe-scheme
solver (full SWE with advection) would improve accuracy for fast-flow channels but is
~100× slower in pure Python/NumPy on the 868×868 grid. Planned as a future upgrade.

Inputs (from upstream pipeline)
--------------------------------
  dem/data/winter_garden_dem.tif       — terrain elevation [m NAVD88]
  dem/data/lake_bed_dem.tif            — lake bed elevation [m]
  dem/data/lake_mask.tif               — binary lake mask
  soil/data/soil_parameters.json       — Horton f0, fc, k (or defaults)
  precipitation/data/atlas14_hyetograph_*.csv — design storm time series

Outputs (saved under simulation/outputs/)
-----------------------------------------
  inundation_depth_{scenario}.tif      — peak water depth [m]
  flow_velocity_{scenario}.tif         — peak velocity magnitude [m/s]
  flood_extent_{scenario}.geojson      — inundation polygon (depth > 0.05m)
  hydrograph_{scenario}.csv            — time series: flooded_ha, lake_rise_m
  lake_vae_curve.csv                   — volume-area-elevation curve

Usage:
    python3 simulation/flood_sim.py
    python3 simulation/flood_sim.py --scenario flash_1hr_100yr --dt 5
    python3 simulation/flood_sim.py --scenario all
"""

import os
import sys
import json
import argparse
import time
import warnings
import numpy as np
import pandas as pd
from scipy import ndimage

# ── GPU detection (PyTorch MPS / CUDA, optional) ─────────────────────────────
try:
    import torch
    if torch.backends.mps.is_available():
        _DEVICE = torch.device("mps")
    elif torch.cuda.is_available():
        _DEVICE = torch.device("cuda")
    else:
        _DEVICE = torch.device("cpu")
    _TORCH_OK = True
except ImportError:
    _TORCH_OK = False
    _DEVICE   = None

BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
OUT_DIR     = os.path.join(BASE_DIR, "outputs")
DEM_DIR     = os.path.join(os.path.dirname(BASE_DIR), "dem", "data")
SOIL_DIR    = os.path.join(os.path.dirname(BASE_DIR), "soil", "data")
PRECIP_DIR  = os.path.join(os.path.dirname(BASE_DIR), "precipitation", "data")

os.makedirs(OUT_DIR, exist_ok=True)

G         = 9.81    # gravity [m/s²]
CFL_ALPHA = 0.5     # Courant number safety factor
MIN_DEPTH = 1e-4    # [m] minimum depth below which flow is zero (wet/dry front)
DEPTH_THRESHOLD = 0.05  # [m] threshold for "flooded" in output GeoJSON
HILLTOP_RAIN_RADIUS_M = 75.0  # [m] radius of the localized rain patch for --rain-mask hilltop

MANNING_N = {
    "water":        0.020,
    "residential":  0.040,  # suburban — houses, lawns, driveways mixed
    "grass_lawn":   0.030,
    "forest":       0.120,
    "pavement":     0.011,
    "default":      0.040,
}

# Horton infiltration presets
# ─────────────────────────────────────────────────────────────────────────────
# SSURGO-raw: soil_parameters.json values (f0=1656 mm/hr for Florahome/Basinger
#   sands) represent the laboratory-measured saturated hydraulic conductivity,
#   which assumes completely dry soil. Under these values all design storms are
#   fully absorbed — Pe=0 everywhere — and the model produces no surface flooding.
#   This reflects the physical reality that Florida's sandy HSG-A soils rarely
#   generate Hortonian (infiltration-excess) overland flow under dry conditions.
#
# central-fl-antecedent: Calibrated for wet-season antecedent moisture typical
#   of Central FL (June–September). Based on Green-Ampt parameters for sandy
#   soils at ~70% initial saturation. f0=76 mm/hr (Ksat × 0.63 deficit fraction),
#   fc=25 mm/hr (NRCS HSG-A minimum saturated rate for shallow water table).
#   k=2.0 hr⁻¹ from Mein & Larson (1973) for fine sands.
#   These produce Hortonian runoff for storms > ~50 mm/hr intensity and are the
#   appropriate parameters for the June–Sep wet season and the target validation
#   event (2024-02-12 was a sustained multi-day event following high lake levels).
#
# Use --soil-preset ssurgo (default, uses soil_parameters.json) or
#     --soil-preset central-fl-antecedent (wet-season calibrated, recommended
#       for viewer demo and for validating against Sentinel-2 flood masks)
SOIL_PRESETS = {
    "central-fl-antecedent": {
        "f0_mm_hr": 76.0,
        "fc_mm_hr": 25.0,
        "k_hr":      2.0,
        "label": "Central FL wet-season antecedent (calibrated for Horton overland flow)",
    },
}

# Scenarios: label → (hyetograph_filename, human_label, data_source)
SCENARIOS = {
    "flash_1hr_100yr":      ("atlas14_hyetograph_1hr_100yr.csv",     "1-hr, 100-year return period",  "NOAA Atlas 14"),
    "flash_1hr_10yr":       ("atlas14_hyetograph_1hr_10yr.csv",      "1-hr, 10-year return period",   "NOAA Atlas 14"),
    "sustained_12hr_100yr": ("atlas14_hyetograph_12hr_100yr.csv",    "12-hr, 100-year return period", "NOAA Atlas 14"),
    "sustained_12hr_10yr":  ("atlas14_hyetograph_12hr_10yr.csv",     "12-hr, 10-year return period",  "NOAA Atlas 14"),
    "historical_20240212":  ("hyetograph_historical_20240212.csv",   "Historical: Feb 7–14, 2024",    "NOAA CDO USC00088788"),
    "historical_gsdr":      ("hyetograph_historical_gsdr.csv",       "Historical: GSDR extreme event (pre-1985, US_086638)", "GSDR US_086638"),
    "historical_gsdr_extreme": ("hyetograph_historical_gsdr_extreme.csv", "Historical: biggest storm in GSDR record (1945-09-16, 245.6mm/24hr)", "GSDR US_086638"),
}


# ── Raster I/O ────────────────────────────────────────────────────────────────

def load_raster(path, dtype=np.float32):
    import rasterio
    if not os.path.exists(path):
        return None, None
    with rasterio.open(path) as src:
        arr     = src.read(1).astype(dtype)
        profile = src.profile.copy()
    return arr, profile


def save_raster(array, profile, out_path, dtype=np.float32):
    import rasterio
    p = profile.copy()
    p.update(count=1, dtype=dtype, compress="lzw")
    with rasterio.open(out_path, "w", **p) as dst:
        dst.write(array.astype(dtype), 1)


def save_geojson(binary_mask, profile, out_path, properties=None):
    import rasterio.features
    import json
    transform = profile["transform"]
    shapes = list(rasterio.features.shapes(
        binary_mask.astype(np.uint8),
        mask=(binary_mask > 0).astype(np.uint8),
        transform=transform,
    ))
    features = []
    for geom, val in shapes:
        if val != 1:
            continue
        feat_props = properties.copy() if properties else {}
        features.append({"type": "Feature", "geometry": geom, "properties": feat_props})
    fc = {"type": "FeatureCollection",
          "crs": {"type": "name", "properties": {"name": str(profile.get("crs","EPSG:4326"))}},
          "features": features}
    with open(out_path, "w") as f:
        json.dump(fc, f)


# ── Horton Infiltration ────────────────────────────────────────────────────────

class HortonInfiltration:
    """
    Spatially uniform Horton infiltration model.
    f(t) = fc + (f0 - fc) * exp(-k * t)
    """

    def __init__(self, f0_mm_hr=112.5, fc_mm_hr=25.0, k_hr=1.8, disabled=False):
        self.f0  = f0_mm_hr / 1000 / 3600   # convert to m/s
        self.fc  = fc_mm_hr  / 1000 / 3600
        self.k   = k_hr      / 3600          # convert to s⁻¹
        self.disabled = disabled             # --no-infiltration: Pe == P exactly

    def rate(self, t_s):
        """Infiltration rate at time t_s [seconds] since storm start [m/s]."""
        if self.disabled:
            return 0.0
        return self.fc + (self.f0 - self.fc) * np.exp(-self.k * t_s)

    def cumulative(self, t_s):
        """Cumulative infiltration F(t) [m]."""
        if self.disabled:
            return 0.0
        if self.k == 0:
            return self.fc * t_s
        return self.fc * t_s + (self.f0 - self.fc) / self.k * (1 - np.exp(-self.k * t_s))

    def effective_rainfall(self, rainfall_rate_ms, t_s):
        """Net rainfall = max(P - f, 0) [m/s]. Short-circuits to raw rainfall when disabled."""
        if self.disabled:
            return rainfall_rate_ms
        return np.maximum(rainfall_rate_ms - self.rate(t_s), 0.0)


# ── Lake VAE Curve ─────────────────────────────────────────────────────────────

class LakeStorageModel:
    """
    Volume-Area-Elevation (VAE) curve for a lake, derived from the lake-bed DEM.
    Supports computing water level from stored volume and vice versa.
    """

    def __init__(self, lake_bed_arr, lake_mask_arr, cell_area_m2, water_surface_elev_m):
        self.cell_area  = cell_area_m2
        self.wse0       = water_surface_elev_m   # initial water surface elevation
        self.bed        = lake_bed_arr[lake_mask_arr > 0]
        self.n_cells    = lake_mask_arr.sum()

        # Build VAE curve: for each elevation level, compute volume
        z_min = float(self.bed.min())
        z_max = water_surface_elev_m + 2.0  # allow 2m above initial WSE
        # Remove any NaN from bed (fall back to water surface so depth = 0)
        self.bed = np.where(np.isfinite(self.bed), self.bed, water_surface_elev_m)

        self.z_levels = np.linspace(z_min, z_max, 200)
        self.volumes  = np.array([
            self.cell_area * float(np.nansum(np.maximum(z - self.bed, 0)))
            for z in self.z_levels
        ])
        self.areas = np.array([
            self.cell_area * float(np.nansum(z > self.bed))
            for z in self.z_levels
        ])
        # Ensure monotonically non-decreasing volumes (interp requirement)
        self.volumes = np.maximum.accumulate(self.volumes)

        # Initial volume at water_surface_elev_m
        self.V0 = float(np.interp(water_surface_elev_m, self.z_levels, self.volumes))

    def wse_from_volume(self, V):
        """Return water surface elevation [m] for a given stored volume [m³]."""
        return float(np.interp(V, self.volumes, self.z_levels))

    def area_from_wse(self, wse):
        """Return lake area [m²] for a given WSE."""
        return float(np.interp(wse, self.z_levels, self.areas))

    def outflow(self, wse, z_outlet, L_outlet=5.0, Cd=1.7):
        """
        Broad-crested weir outflow [m³/s].
        Q = Cd · L · (h_lake - z_outlet)^(3/2)   if h_lake > z_outlet, else 0
        """
        head = wse - z_outlet
        if head <= 0:
            return 0.0
        return Cd * L_outlet * head ** 1.5

    def save_vae_table(self, out_path):
        df = pd.DataFrame({
            "elevation_m_navd88": self.z_levels,
            "volume_m3":          self.volumes,
            "area_m2":            self.areas,
        })
        df.to_csv(out_path, index=False)


# ── Local Inertia 2D Solver ───────────────────────────────────────────────────

def adaptive_dt(h, dx, alpha=CFL_ALPHA):
    """CFL-stable time step [s]."""
    h_max = float(np.max(h))
    if h_max < MIN_DEPTH:
        return 30.0  # no water → use large step
    return alpha * dx / np.sqrt(G * h_max)


def local_inertia_step(h, qx, qy, z, n_grid, dx, dt):
    """
    One time step of the 2D local inertia equations (Bates et al. 2010).

    State variables
    ---------------
    h   : water depth [m],        shape (ny, nx)
    qx  : unit discharge x [m²/s], shape (ny, nx)  (defined at x-interfaces)
    qy  : unit discharge y [m²/s], shape (ny, nx)  (defined at y-interfaces)
    z   : bed elevation [m],       shape (ny, nx)
    n_grid: Manning's n,           shape (ny, nx)
    dx  : cell size [m]
    dt  : time step [s]

    Returns updated (h, qx, qy).
    """
    # Guard against NaN pollution from nodata cells
    h = np.where(np.isfinite(h), h, 0.0)
    z = np.where(np.isfinite(z), z, float(np.nanmean(z)))

    eta = h + z   # water surface elevation [m]

    # ── X-direction fluxes (between columns j and j+1) ─────────────────────
    # h_flow at x-interface: depth available to flow
    eta_i = eta[:, :-1]
    eta_j = eta[:,  1:]
    z_i   = z[:,   :-1]
    z_j   = z[:,    1:]
    hf_x  = np.maximum(eta_i, eta_j) - np.maximum(z_i, z_j)
    hf_x  = np.maximum(hf_x, 0.0)

    n_i = n_grid[:, :-1]
    n_j = n_grid[:,  1:]
    n_x = 0.5 * (n_i + n_j)   # average n at interface

    deta_dx = (eta_j - eta_i) / dx   # water surface slope

    # Flow is zero where insufficient depth
    wet_x = hf_x > MIN_DEPTH
    q_prev_x = qx[:, :-1]

    # Local inertia momentum update
    numerator_x   = q_prev_x - G * hf_x * dt * deta_dx
    denominator_x = 1.0 + G * dt * n_x**2 * np.abs(q_prev_x) / (hf_x ** (7/3) + 1e-12)
    qx_new        = np.where(wet_x, numerator_x / denominator_x, 0.0)

    # Volume-conservation limiter (prevents draining cells below zero on steep slopes)
    # q cannot remove more than h_upstream * dx / (4*dt) from the source cell
    # Factor 4 accounts for up to 4 interfaces (x+, x-, y+, y-) per cell
    h_up_x  = np.where(qx_new >= 0, h[:, :-1], h[:, 1:])
    q_lim_x = h_up_x * dx / (4.0 * dt)
    qx_new   = np.clip(qx_new, -q_lim_x, q_lim_x)

    # ── Y-direction fluxes (between rows i and i+1) ─────────────────────────
    eta_i = eta[:-1, :]
    eta_j = eta[ 1:, :]
    z_i   = z[  :-1, :]
    z_j   = z[   1:, :]
    hf_y  = np.maximum(eta_i, eta_j) - np.maximum(z_i, z_j)
    hf_y  = np.maximum(hf_y, 0.0)

    n_i = n_grid[:-1, :]
    n_j = n_grid[ 1:, :]
    n_y = 0.5 * (n_i + n_j)

    deta_dy = (eta_j - eta_i) / dx

    wet_y = hf_y > MIN_DEPTH
    q_prev_y = qy[:-1, :]

    numerator_y   = q_prev_y - G * hf_y * dt * deta_dy
    denominator_y = 1.0 + G * dt * n_y**2 * np.abs(q_prev_y) / (hf_y ** (7/3) + 1e-12)
    qy_new        = np.where(wet_y, numerator_y / denominator_y, 0.0)

    # Volume-conservation limiter for y-direction
    h_up_y  = np.where(qy_new >= 0, h[:-1, :], h[1:, :])
    q_lim_y = h_up_y * dx / (4.0 * dt)
    qy_new   = np.clip(qy_new, -q_lim_y, q_lim_y)

    # ── Continuity: update water depth ─────────────────────────────────────
    # qx_new[:, j] = flow from cell j to cell j+1 (positive = eastward)
    # Net flux into interior cell j (1..nx-2): inflow from left - outflow to right
    flux_x = np.zeros_like(h)
    flux_x[:, 1:-1] += (qx_new[:, :-1] - qx_new[:, 1:]) * dt / dx
    # West boundary cell 0: only outflow to east → loses water when qx_new[:,0] > 0
    flux_x[:, 0]    -= qx_new[:, 0]  * dt / dx
    # East boundary cell nx-1: only inflow from west → gains water when qx_new[:,-1] > 0
    flux_x[:, -1]   += qx_new[:, -1] * dt / dx

    # qy_new[i, :] = flow from cell i to cell i+1 (positive = southward)
    flux_y = np.zeros_like(h)
    flux_y[1:-1, :] += (qy_new[:-1, :] - qy_new[1:, :]) * dt / dx
    # North boundary row 0: only outflow southward
    flux_y[0,    :]  -= qy_new[0,  :] * dt / dx
    # South boundary row ny-1: only inflow from north
    flux_y[-1,   :]  += qy_new[-1, :] * dt / dx

    # Assemble full qx/qy arrays (same shape as h)
    qx_out = np.zeros_like(h)
    qy_out = np.zeros_like(h)
    qx_out[:, :-1] = qx_new
    qy_out[:-1, :] = qy_new

    h_new = np.maximum(h + flux_x + flux_y, 0.0)

    # Absorbing (outflow) boundaries: water that reaches the domain edge exits freely.
    # Any remaining depth at boundary cells is cleared each step.
    h_new[0, :]  = 0.0   # north edge
    h_new[-1, :] = 0.0   # south edge
    h_new[:, 0]  = 0.0   # west edge
    h_new[:, -1] = 0.0   # east edge

    return h_new, qx_out, qy_out


# ── GPU (PyTorch) version of local_inertia_step ──────────────────────────────

def _local_inertia_step_torch(h, qx, qy, z, n_grid, dx, dt):
    """
    PyTorch equivalent of local_inertia_step — runs on MPS/CUDA/CPU.
    All inputs are float32 torch.Tensors on the same device.
    Returns updated (h, qx, qy) on the same device.
    """
    zero = h.new_zeros(1)

    h = torch.where(torch.isfinite(h), h, zero)
    z_mean = z[torch.isfinite(z)].mean()
    z = torch.where(torch.isfinite(z), z, z_mean)

    eta = h + z

    # ── X-direction fluxes ────────────────────────────────────────────────────
    eta_L, eta_R = eta[:, :-1], eta[:, 1:]
    z_L,   z_R   = z[:,  :-1], z[:,  1:]
    hf_x  = torch.clamp(torch.maximum(eta_L, eta_R) - torch.maximum(z_L, z_R), min=0.0)
    n_x   = 0.5 * (n_grid[:, :-1] + n_grid[:, 1:])
    deta_x = (eta_R - eta_L) / dx
    wet_x  = hf_x > MIN_DEPTH
    q_px   = qx[:, :-1]

    num_x = q_px - G * hf_x * dt * deta_x
    den_x = 1.0 + G * dt * n_x**2 * torch.abs(q_px) / (hf_x**(7/3) + 1e-12)
    qx_new = torch.where(wet_x, num_x / den_x, zero)

    h_up_x  = torch.where(qx_new >= 0, h[:, :-1], h[:, 1:])
    qx_new  = torch.clamp(qx_new, -h_up_x * dx / (4.0 * dt), h_up_x * dx / (4.0 * dt))

    # ── Y-direction fluxes ────────────────────────────────────────────────────
    eta_T, eta_B = eta[:-1, :], eta[1:, :]
    z_T,   z_B   = z[  :-1, :], z[  1:, :]
    hf_y  = torch.clamp(torch.maximum(eta_T, eta_B) - torch.maximum(z_T, z_B), min=0.0)
    n_y   = 0.5 * (n_grid[:-1, :] + n_grid[1:, :])
    deta_y = (eta_B - eta_T) / dx
    wet_y  = hf_y > MIN_DEPTH
    q_py   = qy[:-1, :]

    num_y = q_py - G * hf_y * dt * deta_y
    den_y = 1.0 + G * dt * n_y**2 * torch.abs(q_py) / (hf_y**(7/3) + 1e-12)
    qy_new = torch.where(wet_y, num_y / den_y, zero)

    h_up_y  = torch.where(qy_new >= 0, h[:-1, :], h[1:, :])
    qy_new  = torch.clamp(qy_new, -h_up_y * dx / (4.0 * dt), h_up_y * dx / (4.0 * dt))

    # ── Continuity: update depth ──────────────────────────────────────────────
    flux_x = torch.zeros_like(h)
    flux_x[:, 1:-1] = (qx_new[:, :-1] - qx_new[:, 1:]) * dt / dx
    flux_x[:, 0]   -= qx_new[:, 0]  * dt / dx
    flux_x[:, -1]  += qx_new[:, -1] * dt / dx

    flux_y = torch.zeros_like(h)
    flux_y[1:-1, :] = (qy_new[:-1, :] - qy_new[1:, :]) * dt / dx
    flux_y[0,    :]  -= qy_new[0,  :] * dt / dx
    flux_y[-1,   :]  += qy_new[-1, :] * dt / dx

    qx_out = torch.zeros_like(h)
    qy_out = torch.zeros_like(h)
    qx_out[:, :-1] = qx_new
    qy_out[:-1, :] = qy_new

    h_new = torch.clamp(h + flux_x + flux_y, min=0.0)
    h_new[0, :]  = 0.0
    h_new[-1, :] = 0.0
    h_new[:, 0]  = 0.0
    h_new[:, -1] = 0.0

    return h_new, qx_out, qy_out


# ── Main Simulation ───────────────────────────────────────────────────────────

def run_scenario(scenario_key, scenario_label, hyetograph_path, soil_params,
                 dem_arr, lake_bed_arr, lake_mask_arr, profile,
                 dt_override=None, save_frames=False, frame_interval_min=5,
                 wse_override=None, rain_mask="full", no_infiltration=False):
    """
    Run a single flood scenario end-to-end.

    Parameters
    ----------
    scenario_key       : string identifier for output files
    scenario_label     : human-readable description
    hyetograph_path    : path to atlas14_hyetograph_*.csv (or historical)
    soil_params        : dict from soil_parameters.json
    dem_arr            : DEM array [m]
    lake_bed_arr       : lake bed DEM array [m]
    lake_mask_arr      : binary lake mask
    profile            : rasterio profile dict
    dt_override        : fixed time step [s] (None = adaptive CFL)
    save_frames        : if True, snapshot depth raster at each frame_interval_min step
                         and save to simulation/outputs/depth_frames_{key}.npz
    frame_interval_min : minutes between depth snapshots (default 5; use 30 for 12-hr storms)
    """
    print(f"\n{'='*60}")
    print(f"Scenario: {scenario_label}")
    print(f"{'='*60}")

    if not os.path.exists(hyetograph_path):
        print(f"  ⚠ Hyetograph not found: {hyetograph_path}")
        print("  Run precipitation/noaa_atlas14.py first.")
        return None

    # Load hyetograph
    hyet = pd.read_csv(hyetograph_path)
    times_min  = hyet["time_min"].values
    incr_mm    = hyet["incremental_depth_mm"].values
    dt_hyet_s  = (times_min[1] - times_min[0]) * 60   # hyetograph time step [s]
    total_rain_mm = float(hyet["incremental_depth_mm"].sum())
    print(f"  Total rainfall : {total_rain_mm:.1f} mm over {times_min[-1]/60:.1f} hrs")
    print(f"  Peak intensity : {incr_mm.max() / (dt_hyet_s/3600):.1f} mm/hr")

    # Grid setup
    cell_m = abs(profile["transform"].a)
    ny, nx = dem_arr.shape
    total_cells = ny * nx
    print(f"  Grid           : {ny}×{nx} ({total_cells:,} cells, {cell_m:.1f}m resolution)")

    rain_mask_arr = build_rain_mask(dem_arr, rain_mask, cell_m)
    rain_is_uniform = bool(rain_mask_arr.all())   # True for "full" — take the original scalar code path
    print(f"  Rain mask      : {rain_mask} ({int(rain_mask_arr.sum()):,} of {total_cells:,} cells receive rain)")

    # Manning's n grid (uniform; can be refined with land cover data)
    n_grid = np.full((ny, nx), MANNING_N["residential"], dtype=np.float32)
    n_grid[lake_mask_arr > 0] = MANNING_N["water"]

    # Soil infiltration (use dominant map unit or default)
    if soil_params:
        first = next(iter(soil_params.values()))
        f0_mm_hr = first.get("f0_mm_hr", 112.5)
        fc_mm_hr = first.get("fc_mm_hr",  25.0)
        k_hr     = first.get("k_hr",       1.8)
    else:
        f0_mm_hr, fc_mm_hr, k_hr = 112.5, 25.0, 1.8
        warnings.warn(
            "soil_parameters.json not found — using hardcoded Tavares fine sand defaults "
            "(f0=112.5, fc=25.0, k=1.8). Run soil/fetch_ssurgo.py to get real soil data.",
            UserWarning, stacklevel=2
        )

    horton = HortonInfiltration(f0_mm_hr=f0_mm_hr, fc_mm_hr=fc_mm_hr, k_hr=k_hr, disabled=no_infiltration)
    print(f"  Horton params  : f0={f0_mm_hr:.1f} mm/hr, fc={fc_mm_hr:.1f} mm/hr, k={k_hr:.2f} hr⁻¹"
          + ("  [DISABLED]" if no_infiltration else ""))
    print(f"  Manning's n    : {MANNING_N['residential']:.3f} (residential), {MANNING_N['water']:.3f} (water)")

    # Lake storage model (if lake bed DEM available)
    # Only model lakes that are plausibly water bodies (< 40% of domain)
    lake_model = None
    n_lake_cells = int(lake_mask_arr.sum())
    domain_cells  = lake_mask_arr.size
    lake_fraction = n_lake_cells / domain_cells
    if n_lake_cells > 0 and lake_bed_arr is not None:
        if lake_fraction > 0.40:
            print(f"  ⚠ Lake mask covers {100*lake_fraction:.0f}% of domain — likely over-detection.")
            print("    Re-run dem_process.py to regenerate lake_mask.tif, or treat as no-lake domain.")
            n_lake_cells = 0  # disable lake model for this run
        else:
            # Use authoritative WSE from lake_volume.csv if provided;
            # fall back to DEM mean (which is reliable after largest-component filtering).
            wse0 = wse_override if wse_override is not None else float(dem_arr[lake_mask_arr > 0].mean())
            cell_area = cell_m ** 2
            lake_model = LakeStorageModel(lake_bed_arr, lake_mask_arr, cell_area, wse0)
            vae_path = os.path.join(OUT_DIR, "lake_vae_curve.csv")
            lake_model.save_vae_table(vae_path)
            print(f"  Lake           : {n_lake_cells} cells ({100*lake_fraction:.1f}% of domain), WSE₀={wse0:.2f} m NAVD88")
            print(f"  Initial volume : {lake_model.V0:.0f} m³ ({lake_model.V0/1e6:.3f} × 10⁶ m³)")

    # Initialize state arrays — use GPU (MPS) when available, else CPU numpy
    use_gpu = _TORCH_OK and str(_DEVICE) != "cpu"
    if use_gpu:
        import torch
        _dev = _DEVICE
        z_t  = torch.tensor(dem_arr.copy(), dtype=torch.float32, device=_dev)
        h_t  = torch.zeros((ny, nx), dtype=torch.float32, device=_dev)
        qx_t = torch.zeros((ny, nx), dtype=torch.float32, device=_dev)
        qy_t = torch.zeros((ny, nx), dtype=torch.float32, device=_dev)
        ng_t = torch.tensor(n_grid, dtype=torch.float32, device=_dev)
        print(f"  Solver backend : PyTorch {torch.__version__} on {_dev}")
        z = h = qx = qy = None   # not used in GPU path
    else:
        z   = dem_arr.copy().astype(np.float64)
        h   = np.zeros((ny, nx), dtype=np.float64)
        qx  = np.zeros((ny, nx), dtype=np.float64)
        qy  = np.zeros((ny, nx), dtype=np.float64)
        print(f"  Solver backend : NumPy CPU (install torch for GPU)")

    # Track peak values for output (always numpy/CPU)
    h_peak   = np.zeros((ny, nx), dtype=np.float32)
    vel_peak = np.zeros((ny, nx), dtype=np.float32)

    # Per-timestep frame snapshots (for viewer animation)
    frame_depths       = []   # list of float32 arrays (ny, nx)
    frame_infiltration = []   # list of float32 arrays (ny, nx), cumulative infiltration [mm]
    frame_times        = []   # list of float (minutes)

    # Simulation loop — iterate over hyetograph time steps
    hydrograph_rows = []
    storm_start_s   = 0.0
    V_lake = lake_model.V0 if lake_model else 0.0
    z_outlet = float(dem_arr[lake_mask_arr > 0].max()) if n_lake_cells > 0 else 0.0
    cumulative_infiltration_m = np.zeros((ny, nx), dtype=np.float64)
    lake_cells_bool = lake_mask_arr > 0

    t_wall_start = time.time()
    print(f"\n  Running simulation …")

    for step_i, t_min in enumerate(times_min):
        t_s = t_min * 60   # storm time [seconds]
        rain_rate_scalar = incr_mm[step_i] / 1000 / dt_hyet_s   # [m/s], nominal storm intensity

        if rain_is_uniform:
            # Exact original scalar code path — guarantees --rain-mask full (the default) is a
            # bit-for-bit no-op vs. pre-existing behavior. The array path below is mathematically
            # equivalent but rounds differently on the GPU (float32 tensor cast happens before vs.
            # after the *dt multiply), and the adaptive-CFL feedback loop amplifies that over time.
            Pe_scalar = horton.effective_rainfall(rain_rate_scalar, t_s)
            cumulative_infiltration_m += (rain_rate_scalar - Pe_scalar) * dt_hyet_s
            Pe_report = float(Pe_scalar)
            Pe_lake_sum = Pe_scalar * n_lake_cells
        else:
            rain_rate_arr = np.where(rain_mask_arr, rain_rate_scalar, 0.0)   # (ny, nx) [m/s]
            # Effective rainfall after Horton infiltration (per-cell; zero outside rain_mask_arr)
            Pe_arr = horton.effective_rainfall(rain_rate_arr, t_s)
            # Water actually infiltrated this step (= rain - Pe, naturally zero outside the rain
            # mask and zero everywhere when --no-infiltration is set since Pe_arr == rain_rate_arr)
            cumulative_infiltration_m += (rain_rate_arr - Pe_arr) * dt_hyet_s
            # Mean Pe over the cells that actually receive rain, for logging/hydrograph reporting
            Pe_report = float(Pe_arr[rain_mask_arr].mean()) if rain_mask_arr.any() else 0.0
            # Total rain inflow rate to the lake [m/s summed over lake cells], used per substep
            Pe_lake_sum = float(Pe_arr[lake_cells_bool].sum()) if n_lake_cells > 0 else 0.0
            if use_gpu:
                Pe_t = torch.tensor(Pe_arr.astype(np.float32), device=_dev)

        # Sub-step the hydrodynamic solver within each hyetograph step
        t_substep = 0.0
        while t_substep < dt_hyet_s:
            if use_gpu:
                h_max = float(h_t.max().item())
                dt = (CFL_ALPHA * cell_m / np.sqrt(G * h_max)) if h_max >= MIN_DEPTH else 30.0
            else:
                dt = adaptive_dt(h, cell_m)
            if dt_override is not None:
                dt = float(dt_override)
            dt = min(dt, dt_hyet_s - t_substep)

            if use_gpu:
                h_t = h_t + (Pe_scalar * dt if rain_is_uniform else Pe_t * dt)
                if lake_model is not None:
                    V_lake += Pe_lake_sum * cell_m**2 * dt
                    wse_lake = lake_model.wse_from_volume(V_lake)
                    Q_out = lake_model.outflow(wse_lake, z_outlet, L_outlet=5.0)
                    V_lake = max(V_lake - Q_out * dt, 0.0)
                h_t, qx_t, qy_t = _local_inertia_step_torch(h_t, qx_t, qy_t, z_t, ng_t, cell_m, dt)
                # Bring to CPU for peak tracking (cheap — happens once per substep)
                h_f32 = h_t.cpu().numpy()
                v_mag = (qx_t**2 + qy_t**2).sqrt()
                vel   = torch.where(h_t > 0.01, v_mag / h_t.clamp(min=0.01),
                                    h_t.new_zeros(1)).cpu().numpy()
            else:
                h += Pe_scalar * dt if rain_is_uniform else Pe_arr * dt
                if lake_model is not None:
                    V_lake += Pe_lake_sum * cell_m**2 * dt
                    wse_lake = lake_model.wse_from_volume(V_lake)
                    Q_out = lake_model.outflow(wse_lake, z_outlet, L_outlet=5.0)
                    V_lake = max(V_lake - Q_out * dt, 0.0)
                h, qx, qy = local_inertia_step(h, qx, qy, z, n_grid, cell_m, dt)
                h_f32 = h.astype(np.float32)
                vel   = np.where(h_f32 > 0.01,
                                 np.sqrt(qx**2 + qy**2).astype(np.float32) / np.maximum(h_f32, 0.01),
                                 0.0).astype(np.float32)

            h_peak   = np.maximum(h_peak,   h_f32)
            vel_peak = np.maximum(vel_peak, vel)
            t_substep += dt

        # Record hydrograph at each hyetograph step
        h_np = h_t.cpu().numpy() if use_gpu else h
        flooded_cells = int((h_np > DEPTH_THRESHOLD).sum())
        flooded_ha    = flooded_cells * cell_m**2 / 1e4
        lake_rise_m   = (lake_model.wse_from_volume(V_lake) - lake_model.wse0) if lake_model else 0.0
        mean_depth_m  = float(h_np[h_np > DEPTH_THRESHOLD].mean()) if flooded_cells > 0 else 0.0
        rain_int_mmhr = rain_rate_scalar * 1000 * 3600

        hydrograph_rows.append({
            "time_min":        t_min,
            "rain_mm_hr":      round(rain_int_mmhr, 2),
            "Pe_mm_hr":        round(Pe_report * 1000 * 3600, 2),
            "infilt_mm_hr":    round(horton.rate(t_s) * 1000 * 3600, 2),
            "flooded_ha":      round(flooded_ha, 3),
            "mean_depth_m":    round(mean_depth_m, 3),
            "lake_rise_m":     round(lake_rise_m, 3),
        })

        # Snapshot depth + infiltration frames for viewer animation
        if save_frames and (int(t_min) % frame_interval_min == 0 or step_i == len(times_min) - 1):
            frame_depths.append(h_np.astype(np.float32))
            frame_infiltration.append((cumulative_infiltration_m * 1000.0).astype(np.float32))
            frame_times.append(float(t_min))

        if step_i % max(1, len(times_min)//10) == 0 or step_i == len(times_min)-1:
            elapsed = time.time() - t_wall_start
            print(f"    t={t_min:5.0f}min  rain={rain_int_mmhr:5.1f} mm/hr  "
                  f"Pe={Pe_report*3.6e6:.1f} mm/hr  "
                  f"flooded={flooded_ha:.2f} ha  lake_rise={lake_rise_m:+.3f}m  "
                  f"[{elapsed:.0f}s elapsed]")

    # Post-simulation: run-out (drain for 30 min after rain stops)
    print(f"  Post-storm drainage …")
    for _ in range(60):
        if use_gpu:
            dt_drain = float(dt_override) if dt_override else (
                CFL_ALPHA * cell_m / np.sqrt(G * float(h_t.max().item()))
                if float(h_t.max().item()) >= MIN_DEPTH else 30.0)
            h_t, qx_t, qy_t = _local_inertia_step_torch(h_t, qx_t, qy_t, z_t, ng_t, cell_m, dt_drain)
            h_peak = np.maximum(h_peak, h_t.cpu().numpy())
        else:
            dt_drain = adaptive_dt(h, cell_m) if dt_override is None else float(dt_override)
            h, qx, qy = local_inertia_step(h, qx, qy, z, n_grid, cell_m, dt_drain)
            h_peak = np.maximum(h_peak, h.astype(np.float32))

    # ── Save per-timestep frame snapshots (for viewer animation) ─────────────
    if save_frames and frame_depths:
        frames_path = os.path.join(OUT_DIR, f"depth_frames_{scenario_key}.npz")
        np.savez_compressed(
            frames_path,
            frames=np.stack(frame_depths, axis=0),              # shape: (n_frames, ny, nx) float32, depth [m]
            infiltration_frames=np.stack(frame_infiltration, axis=0),  # cumulative infiltration [mm]
            times_min=np.array(frame_times, dtype=np.float32),
        )
        print(f"  Frame snapshots: {len(frame_depths)} frames → {os.path.basename(frames_path)}")

    # ── Save outputs ──────────────────────────────────────────────────────────
    print(f"\n  Saving outputs for {scenario_key} …")

    depth_path = os.path.join(OUT_DIR, f"inundation_depth_{scenario_key}.tif")
    vel_path   = os.path.join(OUT_DIR, f"flow_velocity_{scenario_key}.tif")
    geojson_path = os.path.join(OUT_DIR, f"flood_extent_{scenario_key}.geojson")
    hydro_path   = os.path.join(OUT_DIR, f"hydrograph_{scenario_key}.csv")

    save_raster(h_peak,   profile, depth_path, dtype=np.float32)
    save_raster(vel_peak, profile, vel_path,   dtype=np.float32)

    flood_mask = (h_peak > DEPTH_THRESHOLD).astype(np.uint8)
    flooded_ha_peak = float(flood_mask.sum()) * cell_m**2 / 1e4
    save_geojson(flood_mask, profile, geojson_path, properties={
        "scenario": scenario_key,
        "total_rain_mm": round(total_rain_mm, 1),
        "flooded_ha": round(flooded_ha_peak, 2),
        "depth_threshold_m": DEPTH_THRESHOLD,
    })

    pd.DataFrame(hydrograph_rows).to_csv(hydro_path, index=False)

    max_depth = float(h_peak.max())
    max_vel   = float(vel_peak.max())
    peak_lake_rise = max(r["lake_rise_m"] for r in hydrograph_rows) if hydrograph_rows else 0.0

    print(f"\n── Results: {scenario_label} ─────────────────────────────")
    print(f"  Total rainfall     : {total_rain_mm:.1f} mm")
    print(f"  Peak flooded area  : {flooded_ha_peak:.2f} ha")
    print(f"  Max water depth    : {max_depth:.2f} m")
    print(f"  Max flow velocity  : {max_vel:.2f} m/s")
    print(f"  Max lake rise      : {peak_lake_rise:+.3f} m")
    print(f"  Depth raster       : {os.path.basename(depth_path)}")
    print(f"  Flood extent GeoJSON: {os.path.basename(geojson_path)}")

    return {
        "scenario": scenario_key,
        "total_rain_mm": total_rain_mm,
        "flooded_ha_peak": flooded_ha_peak,
        "max_depth_m": max_depth,
        "max_velocity_ms": max_vel,
        "max_lake_rise_m": peak_lake_rise,
    }


def build_rain_mask(dem_arr, mode, dx, radius_m=HILLTOP_RAIN_RADIUS_M):
    """
    Boolean (ny, nx) mask of where rain is allowed to fall.

    "full"    : every cell — identical to the model's original (pre-mask) behavior.
    "hilltop" : a disc of radius `radius_m` around the grid's highest-elevation
                cell(s), for the downhill-flow sanity check.
    """
    ny, nx = dem_arr.shape
    if mode == "full":
        return np.ones((ny, nx), dtype=bool)
    if mode == "hilltop":
        finite = np.isfinite(dem_arr)
        max_elev = np.nanmax(dem_arr[finite])
        rows, cols = np.where(finite & (dem_arr == max_elev))
        radius_cells = radius_m / dx
        yy, xx = np.mgrid[0:ny, 0:nx]
        mask = np.zeros((ny, nx), dtype=bool)
        for r, c in zip(rows, cols):
            mask |= (yy - r) ** 2 + (xx - c) ** 2 <= radius_cells ** 2
        return mask
    raise ValueError(f"Unknown rain_mask mode: {mode!r}")


def _largest_component(binary_mask):
    """Keep only the largest connected component of a binary mask."""
    labeled, n = ndimage.label(binary_mask)
    if n == 0:
        return binary_mask
    sizes = ndimage.sum(binary_mask, labeled, range(1, n + 1))
    return (labeled == (np.argmax(sizes) + 1)).astype(np.uint8)


def _load_wse_from_lake_volume(lake_volume_path):
    """
    Read the authoritative water surface elevation from lake_volume.csv.
    Falls back to None if file missing (caller then uses DEM mean).
    """
    if not os.path.exists(lake_volume_path):
        return None
    try:
        df = pd.read_csv(lake_volume_path)
        col = "water_surface_m" if "water_surface_m" in df.columns else "water_surface_elev_m"
        if col in df.columns:
            return float(df[col].iloc[0])
    except Exception:
        pass
    return None


def main(run_scenarios="all", dt_override=None, save_frames=False, soil_preset=None,
         rain_mask="full", no_infiltration=False):
    print("Loading terrain and soil inputs …")

    dem_arr, profile = load_raster(os.path.join(DEM_DIR, "winter_garden_dem.tif"))
    if dem_arr is None:
        sys.exit("DEM not found. Run dem/dem_download.py first.")

    # Replace NaN/nodata with the domain mean (NaN propagates and breaks the solver)
    nodata_val = profile.get("nodata", None)
    nan_mask = ~np.isfinite(dem_arr)
    if nodata_val is not None:
        nan_mask |= (dem_arr == nodata_val)
    if nan_mask.any():
        fill_val = float(np.nanmean(dem_arr))
        dem_arr[nan_mask] = fill_val
        print(f"  Filled {nan_mask.sum():,} nodata cells in DEM with mean elevation {fill_val:.1f}m")

    # Prefer FWC bathymetric survey; fall back to shoreline-slope estimate
    _fwc_path = os.path.join(DEM_DIR, "lake_bed_dem_fwc.tif")
    _est_path = os.path.join(DEM_DIR, "lake_bed_dem_estimated.tif")
    _bed_path = _fwc_path if os.path.exists(_fwc_path) else _est_path
    lake_bed_arr, _ = load_raster(_bed_path)
    if lake_bed_arr is not None:
        print(f"  Lake bed source: {os.path.basename(_bed_path)}")
    lake_mask_arr, _= load_raster(os.path.join(DEM_DIR, "lake_mask.tif"), dtype=np.uint8)
    if lake_mask_arr is None:
        lake_mask_arr = np.zeros_like(dem_arr, dtype=np.uint8)
    else:
        # Keep only Johns Lake (largest component) — drops 5 irrigation ponds/canals
        raw_cells = int((lake_mask_arr > 0).sum())
        lake_mask_arr = _largest_component(lake_mask_arr > 0)
        filt_cells = int(lake_mask_arr.sum())
        print(f"  Lake mask      : filtered {raw_cells:,} → {filt_cells:,} cells (largest component = Johns Lake)")

    # Authoritative WSE from lake_volume.csv (FWC bathymetry + OWM consensus)
    # Overrides the DEM-mean approach used in LakeStorageModel to avoid bias
    # from the hydro-flattened DEM surface.
    _lv_path = os.path.join(DEM_DIR, "lake_volume.csv")
    _wse_override = _load_wse_from_lake_volume(_lv_path)
    if _wse_override is not None:
        print(f"  WSE₀ override  : {_wse_override:.3f} m NAVD88 (from lake_volume.csv)")

    if lake_bed_arr is None:
        lake_bed_arr = dem_arr.copy()
        print("  ⚠ lake_bed_dem_estimated.tif not found; using DEM as lake bed (run dem_process.py first)")
    else:
        # Fix NaN in lake bed
        lb_nan = ~np.isfinite(lake_bed_arr)
        if lb_nan.any():
            lake_bed_arr[lb_nan] = dem_arr[lb_nan]

    # Load soil parameters
    soil_params = None
    if soil_preset and soil_preset in SOIL_PRESETS:
        preset = SOIL_PRESETS[soil_preset]
        print(f"  Soil preset     : {soil_preset}")
        print(f"    {preset['label']}")
        print(f"    f0={preset['f0_mm_hr']} mm/hr, fc={preset['fc_mm_hr']} mm/hr, k={preset['k_hr']} hr⁻¹")
        # Build a soil_params dict in the same format as soil_parameters.json
        soil_params = {"__preset__": {
            "f0_mm_hr": preset["f0_mm_hr"],
            "fc_mm_hr": preset["fc_mm_hr"],
            "k_hr":     preset["k_hr"],
        }}
    else:
        soil_path = os.path.join(SOIL_DIR, "soil_parameters.json")
        if os.path.exists(soil_path):
            with open(soil_path) as f:
                soil_params = json.load(f)
            first = next(iter(soil_params.values()))
            f0 = first.get("f0_mm_hr", 112.5)
            fc = first.get("fc_mm_hr",  25.0)
            print(f"  Soil parameters : loaded from {soil_path}")
            print(f"    First map unit: f0={f0:.1f} mm/hr, fc={fc:.1f} mm/hr")
            if f0 > 500:
                print(f"  ⚠ f0={f0:.0f} mm/hr is very high (raw SSURGO Ksat for dry soil).")
                print("    All design storms will be fully absorbed — Pe=0, no surface flooding.")
                print("    For wet-season surface runoff modeling, use:")
                print("      --soil-preset central-fl-antecedent")
        else:
            print("  ⚠ soil_parameters.json not found; using Sandy soil defaults (Orange County FL)")

    # Select which scenarios to run (skip historical if hyetograph not yet fetched)
    if run_scenarios == "all":
        to_run = list(SCENARIOS.keys())
    else:
        to_run = [run_scenarios] if run_scenarios in SCENARIOS else list(SCENARIOS.keys())

    results = []
    for key in to_run:
        hyet_file, label, _ = SCENARIOS[key]
        hyet_path = os.path.join(PRECIP_DIR, hyet_file)
        if not os.path.exists(hyet_path):
            print(f"\n  ⚠ Skipping {key}: {hyet_file} not found in {PRECIP_DIR}")
            if key == "historical_20240212":
                print("    Run: python3 precipitation/fetch_noaa_gauge.py")
            continue

        # Default frame interval: 5 min for 1-hr storms, 30 min for 12-hr storms
        frame_interval = 30 if "12hr" in key else 5

        res = run_scenario(
            scenario_key=key,
            scenario_label=label,
            hyetograph_path=hyet_path,
            soil_params=soil_params,
            dem_arr=dem_arr.copy(),
            lake_bed_arr=lake_bed_arr.copy() if lake_bed_arr is not None else None,
            lake_mask_arr=lake_mask_arr.copy(),
            profile=profile,
            dt_override=dt_override,
            save_frames=save_frames,
            frame_interval_min=frame_interval,
            wse_override=_wse_override,
            rain_mask=rain_mask,
            no_infiltration=no_infiltration,
        )
        if res:
            results.append(res)

    if results:
        summary = pd.DataFrame(results)
        summary_path = os.path.join(OUT_DIR, "simulation_summary.csv")
        summary.to_csv(summary_path, index=False)
        print(f"\n\nAll scenarios saved to {OUT_DIR}/")
        print(f"Summary table: {summary_path}")
        print("\n" + summary.to_string(index=False))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run 2D flood simulation for Winter Garden FL property")
    parser.add_argument("--scenario", type=str, default="all",
                        choices=list(SCENARIOS.keys()) + ["all"],
                        help="Scenario to run (default: all)")
    parser.add_argument("--dt", type=float, default=None,
                        help="Fixed time step [s] (default: adaptive CFL)")
    parser.add_argument("--save-frames", action="store_true",
                        help="Save per-timestep depth raster snapshots as depth_frames_{scenario}.npz "
                             "(needed for viewer animation; adds ~5-15s per scenario)")
    parser.add_argument("--soil-preset", type=str, default=None,
                        choices=list(SOIL_PRESETS.keys()),
                        help="Override SSURGO soil parameters with a calibrated preset. "
                             "'central-fl-antecedent' uses wet-season antecedent moisture "
                             "conditions (f0=76, fc=25 mm/hr) — recommended for viewer demo "
                             "and Sentinel-2 flood validation.")
    parser.add_argument("--rain-mask", type=str, default="full", choices=["full", "hilltop"],
                        help="'full' (default) rains uniformly over the whole grid — identical "
                             "to pre-existing behavior. 'hilltop' confines rain to a "
                             f"{HILLTOP_RAIN_RADIUS_M:.0f}m-radius disc around the grid's "
                             "highest-elevation cell(s), for a downhill-flow physics sanity check.")
    parser.add_argument("--no-infiltration", action="store_true",
                        help="Disable Horton infiltration (Pe == P exactly), for isolating "
                             "overland-flow physics from soil absorption in sanity checks.")
    args = parser.parse_args()
    main(args.scenario, args.dt, save_frames=args.save_frames, soil_preset=args.soil_preset,
         rain_mask=args.rain_mask, no_infiltration=args.no_infiltration)
