# deepearth/models/flowering_light.yaml
# LIGHTWEIGHT DeepEarth Configuration for Fast Iteration
# ════════════════════════════════════════════════════════════════════════════

# Architecture dimensions (minimal viable sizes)
universal_dim: 256  # Reduced from 1024
spacetime_dim: 128  # Reduced from 512
dataset_embed_dim: 2
modality_embed_dim: 2
encoder_embed_dim: 2
mask_embed_dim: 4
context_position_dim: 0
modality_position_dim: 0

# Training parameters
batch_size: 32  # Increased since model is smaller
learning_rate: 0.001
weight_decay: 0.01
num_epochs: 10
gradient_clip: 1.0
mixed_precision: true
compile_model: false  # Earth4D HashEncoder incompatible

# Masking strategy
mask_spacetime_prob: 0.10
mask_data_prob: 0.15
mask_dataset_prob: 0.02
mask_modality_prob: 0.05
mask_encoder_prob: 0.05

# LIGHTWEIGHT Main Perceiver (drastically reduced)
context_window: 16  # Reduced from 64
num_latents: 64     # Reduced from 512
latent_dim: 128     # Reduced from 768
num_blocks: 2       # Reduced from 6
num_cross_attention_heads: 4  # Reduced from 8
num_self_attention_heads: 4   # Reduced from 8
dropout: 0.1

# PerceiverProjector architecture (keep minimal)
projector_config:
  num_latents: 16      # Reduced from 64
  latent_dim: 32       # Reduced from 64
  num_blocks: 1        # Reduced from 2
  num_cross_attention_heads: 2
  num_self_attention_heads: 2
  dropout: 0.1

# Maximum cardinalities
max_datasets: 10
max_modalities: 10
max_encoders: 10

# Sampling strategy
sampling_strategy:
  clusters_per_context: 4  # Reduced from 8
  samples_per_cluster: 4   # Reduced from 32
  time_of_day_weight: 0.05
  time_of_year_weight: 0.35
  time_of_history_weight: 0.10
  spatial_weight: 0.25
  modality_weight: 0.15
  universal_weight: 0.10
  sampling_type: probabilistic

# UMAP configuration
umap_dim: 1
umap_max_samples: 10000  # Reduced for speed
umap_n_neighbors: 15
umap_min_dist: 0.1

# Evaluation splits
test_ratio: 0.2

# Spatial holdouts
spatial_holdouts:
  - type: percentage
    lat_pct: 0.05
    lon_pct: 0.05
    min_separation_pct: 0.2

# Temporal holdouts
temporal_holdouts:
  - type: percentage
    value: 0.15
    position: end
    min_separation_pct: 0.1

# Coordinate system
coordinate_system: ecef
time_range: [1900, 2100]
spatial_dims: 3

# Earth4D configuration (use defaults, just control projection)
earth4d_config:
  skip_projection: true  # Skip PerceiverProjector, use native dimension (162D)

# Hardware
device: cuda
num_workers: 4
pin_memory: true

# Cache directory
cache_dir: ./cache
regenerate_cache: false

# Random seed
seed: 42

# Output directory
output_dir: ./experiments/angiosperm_light